FROM oven/bun:1.4.0-alpine

WORKDIR /app

COPY package.json bun.lock tsconfig.json ./
COPY apps/backend/package.json ./apps/backend/package.json

RUN bun install --frozen-lockfile --production

COPY apps/backend ./apps/backend

WORKDIR /app/apps/backend

ENV NODE_ENV=production

EXPOSE 10000

USER bun

CMD ["bun", "run", "start"]
